// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.generic.persistence;

import br.com.kamaleon.generic.persistence.GenericDAO;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GenericDAO_Roo_Configurable {
    
    declare @type: GenericDAO: @Configurable;
    
}
