// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.projeto.atividade;

import br.com.kamaleon.business.projeto.atividade.AtividadeHistorico;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AtividadeHistorico_Roo_Configurable {
    
    declare @type: AtividadeHistorico: @Configurable;
    
}
