// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.empesa.setor;

import br.com.kamaleon.business.empesa.setor.Setor;

privileged aspect Setor_Roo_JavaBean {
    
    public String Setor.getDescricao() {
        return this.descricao;
    }
    
    public void Setor.setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
}
