// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.pessoa.funcionario;

import br.com.kamaleon.business.pessoa.funcionario.Funcionario;
import javax.persistence.Entity;

privileged aspect Funcionario_Roo_Jpa_Entity {
    
    declare @type: Funcionario: @Entity;
    
}
