// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.pessoa.usuario;

import br.com.kamaleon.business.pessoa.usuario.Grupo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Grupo_Roo_Configurable {
    
    declare @type: Grupo: @Configurable;
    
}
