// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.pessoa.usuario;

import br.com.kamaleon.business.pessoa.usuario.Usuario;
import javax.persistence.Entity;

privileged aspect Usuario_Roo_Jpa_Entity {
    
    declare @type: Usuario: @Entity;
    
}
