// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.pessoa.empresa;

import br.com.kamaleon.business.pessoa.empresa.Empresa;
import javax.persistence.Entity;

privileged aspect Empresa_Roo_Jpa_Entity {
    
    declare @type: Empresa: @Entity;
    
}
