// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.projeto.modulo;

import br.com.kamaleon.business.projeto.modulo.Modulo;
import javax.persistence.Entity;

privileged aspect Modulo_Roo_Jpa_Entity {
    
    declare @type: Modulo: @Entity;
    
}
