// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.projeto.modulo;

import br.com.kamaleon.business.projeto.modulo.SubModulo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SubModulo_Roo_Configurable {
    
    declare @type: SubModulo: @Configurable;
    
}
