// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.generic;

import br.com.kamaleon.generic.CodigoKamaleon;
import javax.persistence.MappedSuperclass;

privileged aspect CodigoKamaleon_Roo_Jpa_Entity {
    
    declare @type: CodigoKamaleon: @MappedSuperclass;
    
}
