// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.generic;

import br.com.kamaleon.generic.CodigoKamaleon;

privileged aspect CodigoKamaleon_Roo_JavaBean {
    
    public Long CodigoKamaleon.getId() {
        return this.id;
    }
    
    public void CodigoKamaleon.setId(Long id) {
        this.id = id;
    }
    
}
