// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.projeto.versao;

import br.com.kamaleon.business.projeto.versao.Versao;
import javax.persistence.Entity;

privileged aspect Versao_Roo_Jpa_Entity {
    
    declare @type: Versao: @Entity;
    
}
