// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.projeto;

import br.com.kamaleon.business.projeto.Projeto;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Projeto_Roo_Configurable {
    
    declare @type: Projeto: @Configurable;
    
}
