// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.kamaleon.business.pessoa.cliente;

import br.com.kamaleon.business.pessoa.cliente.Cliente;
import javax.persistence.Entity;

privileged aspect Cliente_Roo_Jpa_Entity {
    
    declare @type: Cliente: @Entity;
    
}
